name: b1_test_app
description: Offline-first daily drill MCQ practice app with spaced repetition.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.4
  path: ^1.9.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  file_picker: ^13.1.0
  intl: ^0.20.2
  krutidevtounicode: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_bns_10.json
